version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - proxy.example.com
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  service1:
    hostname: kbr_service1_1.kbr_envoymesh
    build:
      context: .
      dockerfile: Dockerfile-service-kbr
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service.example.com
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  service2:
    hostname: kbr_service2_1.kbr_envoymesh
    build:
      context: .
      dockerfile: Dockerfile-service-kbr
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service2.example.com
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  kdc:
    build:
      context: .
      dockerfile: Dockerfile-masterkdc
    networks:
      envoymesh:
        aliases:
          - kerberos.example.com
    expose:
      - "88"
      - "749"

  client:
    build:
      context: .
      dockerfile: Dockerfile-client-kbr
    networks:
      - envoymesh

networks:
  envoymesh: {}
