FROM ubuntu:16.04
RUN apt-get update && apt-get install -y supervisor
RUN export DEBIAN_FRONTEND=noninteractive
# RUN apt -y -qq install krb5-kdc
RUN apt -y install krb5-admin-server
RUN apt -y install krb5-config
RUN apt -y install vim
RUN mkdir /usr/local/var
RUN mkdir /usr/local/var/log
ADD ./krb5.conf /etc
# ADD ./kdc.conf /etc/krb5kdc
# RUN kdb5_util create -r EXAMPLE.COM -P yoda
# ADD ./kadm5.acl /etc/krb5kdc
# RUN kadmin.local -q "addprinc -pw yoda admin/admin@EXAMPLE.COM"

ADD ./supervisor.conf /etc
ADD ./kadmind.sv.conf /etc/supervisor/conf.d
ADD ./kadmin.sv.conf /etc/supervisor/conf.d
# ADD ./krb5kdc.sv.conf /etc/supervisor/conf.d
CMD supervisord -c /etc/supervisor.conf
